### PR TITLE
add Portuguese translation

### PR DESCRIPTION
**Pull request by alexweber**

### CODE REVIEW

**Comment by alexweber** [comment]
@clux Presumably tests not necessary? Same applies to #3  thx!

**Comment by clux** [comment]
It would be preferable if you had some tests. Even if you just copy-paste it from another file and change some constants. If some language needs to extend the main file, I can't guarantee other languages will stay working without tests if I need to refactor it.

**Comment by clux** [comment]
Ah, but you are using the same implementation as English. Never mind. Yeah, that should be fine.

**Comment by clux** [comment]
Both look good. Thank you. Will bump a minor later today.

**Pull request merged**
